In [29]:
import numpy as np
import pandas as pd
import os
import shutil
from subprocess import Popen, PIPE
from IPython.display import clear_output
import time

In [1]:
import numpy as np
from sklearn.metrics import f1_score

In [8]:
MISE = []
mains = []
interactions = []
features = []
fprs_main = []
fnrs_main = []
f1s_main = []
fprs_interaction = []
fnrs_interaction = []
f1s_interaction = []
f1s_feature = []

data = 'large-synthetic-correlated'
dist = 'normal'
correlation = 0.7 # default value of 0.0 for 'synthetic' data
train_size = 10000
version = 1
for seed in np.arange(100):
    filename = f'/home/gridsan/shibal/elaan/results/{data}/{dist}/N_train_{train_size}/seed{seed}/EBM/v{version}'
    
    try:
        with open(filename+'/Results.txt') as file:
            lines = file.readlines()
            mise = float([line for line in lines if "True" in line][0].split(" ")[-1].split("\n")[0])
            MISE.append(mise)
            fpr_main = float([line for line in lines if "FPR (main)" in line][0].split(" ")[-1].split("\n")[0])
            fprs_main.append(fpr_main)
            fnr_main = float([line for line in lines if "FNR (main)" in line][0].split(" ")[-1].split("\n")[0])
            fnrs_main.append(fnr_main)
            f1_main = float([line for line in lines if "F1 (main)" in line][0].split(" ")[-1].split("\n")[0])
            f1s_main.append(f1_main)
            fpr_interaction = float([line for line in lines if "FPR (interactions)" in line][0].split(" ")[-1].split("\n")[0])
            fprs_interaction.append(fpr_interaction)
            fnr_interaction = float([line for line in lines if "FNR (interactions)" in line][0].split(" ")[-1].split("\n")[0])
            fnrs_interaction.append(fnr_interaction)
            f1_interaction = float([line for line in lines if "F1 (interactions)" in line][0].split(" ")[-1].split("\n")[0])
            f1s_interaction.append(f1_interaction)
            print("Seed: ", seed, " mise:", mise)
            
        with open(filename+'/support_set.npy', 'rb') as f:
            main_set = np.load(f)
            interaction_set = np.load(f)
            mains.append(main_set)
            interactions.append(interaction_set)
            feature_set = np.unique(list(main_set)+list(np.unique(interaction_set)))
            features.append(feature_set)
            if data=='large-synthetic-correlated':
                p = 500
                k = 10
                feature_support_truth = np.zeros(p)
                true_support = np.arange((int)(p/(2*k)),p,(int)(p/k))
                feature_support_truth[true_support] = 1
                feature_support_recovered = np.zeros(p)
                feature_support_recovered[feature_set] = 1
                f1_feature = f1_score(feature_support_truth, feature_support_recovered)
                f1s_feature.append(f1_feature)
    except:
        pass

Seed:  1  mise: 3.4852278842257722
Seed:  2  mise: 3.5410799455996327
Seed:  3  mise: 4.039129383165811
Seed:  4  mise: 3.793778609427469
Seed:  5  mise: 3.465656028209905
Seed:  6  mise: 3.490305656774387
Seed:  7  mise: 3.7718835601243903
Seed:  8  mise: 3.9229431993584587
Seed:  9  mise: 3.80545401127087
Seed:  10  mise: 3.609697587719771
Seed:  11  mise: 3.960120228357483
Seed:  12  mise: 3.8386747873206417
Seed:  13  mise: 3.756610718419096
Seed:  14  mise: 3.554186100565591
Seed:  15  mise: 3.701338035228724
Seed:  16  mise: 3.775456810095343
Seed:  17  mise: 3.6853571427647256
Seed:  18  mise: 3.834772454722091
Seed:  19  mise: 3.862577768348252
Seed:  20  mise: 3.754860978987213
Seed:  21  mise: 3.9243681418394285
Seed:  22  mise: 3.684966713800946
Seed:  23  mise: 4.10983638640501
Seed:  24  mise: 3.696148374339621
Seed:  25  mise: 3.8670799695043163


In [9]:
len(MISE)

25

In [10]:
print("MISE:", np.mean(MISE), "std-err:", np.std(MISE)/np.sqrt(len(MISE)))
print("FPR (main):", np.mean(fprs_main), "std-err:", np.std(fprs_main)/np.sqrt(len(fprs_main)))
print("FNR (main):", np.mean(fnrs_main), "std-err:", np.std(fnrs_main)/np.sqrt(len(fnrs_main)))
print("F1 (main):", np.mean(f1s_main), "std-err:", np.std(f1s_main)/np.sqrt(len(f1s_main)))
print("FPR (interactions):", np.mean(fprs_interaction), "std-err:", np.std(fprs_interaction)/np.sqrt(len(fprs_interaction)))
print("FNR (interactions):", np.mean(fnrs_interaction), "std-err:", np.std(fnrs_interaction)/np.sqrt(len(fnrs_interaction)))
print("F1 (interactions):", np.mean(f1s_interaction), "std-err:", np.std(f1s_interaction)/np.sqrt(len(f1s_interaction)))
print("F1 (features):", np.mean(f1s_feature), "std-err:", np.std(f1s_feature)/np.sqrt(len(f1s_feature)))


MISE: 3.7572604190629977 std-err: 0.03340873436054321
FPR (main): 1.0 std-err: 0.0
FNR (main): 0.0 std-err: 0.0
F1 (main): 0.0392156862745098 std-err: 0.0
FPR (interactions): 0.00040852319186799766 std-err: 3.975296520920859e-05
FNR (interactions): 0.455 std-err: 0.01714642819948225
F1 (interactions): 0.171963243130746 std-err: 0.020626702375691072
F1 (features): 0.0392156862745098 std-err: 0.0


In [19]:
# np.unique(np.concatenate(mains).ravel(), return_counts=True)

(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
        130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
        156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
        169, 170, 171, 172, 173, 174, 175, 176, 177

In [12]:
# interactions = [inter for inter in interactions if len(inter)>0]
# np.unique(np.concatenate(interactions, axis=0), return_counts=True, axis=0)

(array([[  0,  45],
        [  0, 156],
        [  0, 279],
        ...,
        [472, 492],
        [473, 476],
        [475, 483]]),
 array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1, 14,  1,  1,  1,  1,  1,  1, 12, 19,  9,  1,  1,
         1,  2, 11,  1,  1,  1,  1,  4,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  